version: "3.8"

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:13.0-alpine
    container_name: device-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: device-backend
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - ./backend:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn bigcorp.wsgi:application --bind 0.0.0.0:8000
      "

  redis:
    image: redis:7.2.3-alpine
    container_name: device-redis
    restart: unless-stopped

  celery:
    build: ./backend
    container_name: device-celery
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - static_data:/app/static
      - ./backend:/app
    restart: always
    command: >
      sh -c "
      celery -A bigcorp worker --loglevel=info
      "

  nginx:
    image: nginx:latest
    container_name: device-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
    ports:
      - 80:80
    restart: always
