# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libpq-dev gcc python3-dev libpango-1.0-0 libpangoft2-1.0-0 gobject-introspection && \
    apt-get clean

# Set work directory
WORKDIR /app

# Copy requirements.txt to the container
COPY requirements.txt /app/

# Install Python dependencies 
RUN python -m pip install --upgrade pip --no-warn-script-location && \
    pip install -r requirements.txt --no-cache-dir --no-warn-script-location

# Copy the rest of the application code to the container
COPY . /app/

# Expose the port on which the Django app runs
EXPOSE 8000
