# Generated by Django 5.0.4 on 2024-05-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('sensors_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('sensors_number', models.IntegerField(default=0)),
                ('сity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.city')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Time when sensor was set up')),
                ('modified_at', models.TimeField(auto_now=True, verbose_name='Time when something in it was changed')),
                ('address', models.CharField(max_length=100, verbose_name='The place where it was installed')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.city', verbose_name='The city it is located at')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.district', verbose_name='The area it is located at')),
            ],
        ),
    ]
