# Generated by Django 5.0.4 on 2024-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='full_bins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='full_bins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='address',
            field=models.CharField(max_length=100, verbose_name='The address where it was installed'),
        ),
    ]
