# Generated by Django 5.0.4 on 2024-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_city_full_bins_district_full_bins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='сity',
            new_name='city',
        ),
    ]
