# Generated by Django 5.0.4 on 2024-05-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('full', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.sensor')),
            ],
            options={
                'verbose_name': 'Запись',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='RecordProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.record',),
        ),
    ]
